# Generated by Django 2.2 on 2020-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanapka', '0002_menuitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
