# Generated by Django 2.2 on 2020-02-12 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanapka', '0003_menuitem_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
